### DISCUSSION TITLE
How to set up Config File?

### DISCUSSION THREAD

**Discussion by orion-miller** [posativ/isso#923] [Q&A]
I'm new to Isso and having some issues getting set up. I am trying to follow the instructions here: https://isso-comments.de/docs/reference/installation/#using-docker

![image](https://user-images.githubusercontent.com/33074666/186309412-21124e42-8284-4d39-b272-c9f507d40708.png)

It says here before running the image in Docker to have your configuration in "/var/lib/isso", but under what parent directory is the var folder supposed to be located? I cloned the repo and updated the fields of the config file, but under what folder do I make the /var/lib/isso subfolders where Docker will be able to recognize it?

Apologies if I am missing something that should be self-explanatory here, but I'm new to this.

**Comment by PierceNg** [comment]
Both ```/var/lib/isso``` and ```/db/comments.db``` are from the perspective of the Docker container. From the host's perspective, you could create bind-mounts so that the container sees those locations/files.

My docker-compose.yml has these bind-mounts:

```
services:
  isso:
    container_name: isso
    hostname: isso
    image: samadhiweb/isso:0.13.0
    networks: 
      - nginxnet
    volumes:
      - type: bind
        source: ./isso.cfg
        target: /config/isso.cfg
      - type: bind
        source: ./extra_hosts_data
        target: /config/extra_hosts_data
      - type: bind
        source: ./runtime
        target: /runtime
    restart: unless-stopped
```

For ```isso.cfg```, the container sees it as ```/config/isso.cfg```, which is the host's ```./isso.cfg``` through the bind-mount. Within the config file, ```dbpath = /runtime/comments.db```, and what the container sees as ```/runtime/comments.db``` is the host's ```./runtime/comments.db``` directory again through Docker bind-mount.

How are you running the Docker container?
