### DISCUSSION TITLE
Gunicorn 400 Missing URI Query in Docker

### DISCUSSION THREAD

**Discussion by aetherith** [posativ/isso#984] [Q&A]
## Checklist
- [x] I am running the latest version. **Using `ghcr.io/isso-comments/isso:0.13.0` image**
- [x] I have checked the [troubleshooting guide](https://isso-comments.de/docs/guides/troubleshooting/)
- [x] I have searched the [open issues](https://github.com/posativ/isso/issues), but my issue has not already been reported

## What is not working?
I am migrating a previous non-containerized Isso (0.12.2) install to a new containerized install (0.13.0) running with Podman behind a NGINX reverse proxy. I am able to get the container to run and parse my configuration file but when I try to connect to any of the pages I get a 400/404 errors from `gunicorn`.

Both `curl -v https://comments.example.com` and `curl -v http://localhost:8080` both give the same error, the only difference being the contents of the `Server` header. The first reports `nginx` since that's the reverse proxy URL and the second reports `gunicorn` because it's a direct connection.

When connecting to `https://comments.example.com/` the error is `400 - missing uri query` and when connecting to `https://comments.example.com/example.com/admin` the error is `404 - Not Found`.

## How can one reproduce this issue?

This is my `isso.cfg` which happens to be using a different name in my install and the path overwritten with `ISSO_SETTINGS` environment variable.

```ini
[general]
name = example.com
dbpath = /db/example.com.db
host = https://example.com

[admin]
enabled = true
password = REDACTED
```

Both the config file and DB are from my old installation and were only modified to account for the new DB path.

The container configuration is a little tricky since I'm using Ansible, but here's the Ansible and my best attempt at parsing out the raw Podman command. I am running Podman 4.6.1 on Fedora 38.

```yaml
- name: Create Isso container
  become: true
  containers.podman.podman_container:
    name: isso
    image: ghcr.io/isso-comments/isso:0.13.0
    user: 992
    volume:
      - "/opt/isso:/config"
      - "/opt/isso:/db"
    ports:
      - "127.0.0.1:8080:8080"
    env:
      ISSO_SETTINGS: /config/example.com.cfg
    rm: true
    state: present
```

```bash
podman run \
  --detach \
  --env "ISSO_SETTINGS=/config/example.com.cfg" \
  --name isso \
  --publish 127.0.0.1:8080:8080 \
  --rm \
  --user 992 \
  --volume /opt/isso:/config \
  --volume /opt/isso:/db \
  ghcr.io/isso-comments/isso:0.13.0
```
