### ISSUE TITLE
Comments do not load *almost working*, mixed content warning

### ISSUE THREAD

**Issue by MrCappuccino** [posativ/isso#573]
### I have my gohugo blog set up to auto deploy with netlify, which works perfectly, and I'm now trying to add isso comments to it, but I have been bashing my head against the wall **all day**, without being able to fix it.

My setup:

- Nginx
- docker-compose
- another VPS to host isso
- Netlify to host GoHugo blog

https://Aerial.ml is my blog and https://TooDoo.ml is the hostname for the server hosting isso.

> `Mixed Content: The page at 'https://aerial.ml/posts/welcome/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://toodoo.ml/?uri=%2Fposts%2Fwelcome%2F&nested_limit=5'. This request has been blocked; the content must be served over HTTPS.`

**Adding a comment, however seems to work, as it does get added to the database:**

`isso_1     | 2019-09-17 20:49:25,006 INFO: comment created: {"id": 14, "parent": null, "created": 1568753364.9753194, "modified": null, "mode": 1, "text": "<p>Test adding new comment</p>", "author": "test name", "website": "http://testwebsite.com", "likes": 0, "dislikes": 0, "notification": 0, "hash": "f715428439fd"}
nginx      | 167.99.137.12 - - [17/Sep/2019:20:49:25 +0000] "POST /new?uri=%2Fposts%2Fwelcome%2F HTTP/1.1" 201 258 "https://aerial.ml/posts/welcome/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36"`

And a temporary comment appears (dissapears upon refresh):
![image](https://user-images.githubusercontent.com/10047484/65078618-e3ae2380-d98c-11e9-9db7-bcab84a6ad69.png)

This is my **nginx.conf**:
```worker_processes auto;                                

events {                  
    multi_accept on;
}                                                       

http {                                                                  
    include       /etc/nginx/mime.types;              
    default_type  application/octet-stream;        

    log_format compression '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $upstream_addr '
        '"$http_referer" "$http_user_agent"';

    server {                                                            
        listen 80 default_server;            
        listen [::]:80 default_server;  

        server_name toodoo.ml;

        return 301 https://$host$request_uri;                               
    }                                                                                    

    upstream isso {                                                                       
        server isso:8082;
    }                                                       

    server {                                                
        listen 443 ssl;                                               
        server_name toodoo.ml; 

        server_tokens off; # remove nginx version banner
        ssl_certificate /etc/letsencrypt/live/toodoo.ml/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/toodoo.ml/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        ## Start: Size Limits & Buffer Overflows ##
        client_body_buffer_size  1K;
        client_header_buffer_size 1k;
        client_max_body_size 1k;
        large_client_header_buffers 2 1k;
        ## END: Size Limits & Buffer Overflows ##

        # avoid clickjacking
        add_header X-Frame-Options SAMEORIGIN;
        # disable content-type sniffing
        add_header X-Content-Type-Options nosniff;
        # Enable XSS filter
        add_header X-XSS-Protection "1; mode=block";

        location / {
            proxy_pass http://isso;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Script-Name /;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;

            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' 'http://Aerial.ml';
                add_header 'Access-Control-Allow-Methods' 'HEAD, GET, POST, PUT, DELETE';
                add_header 'Access-Control-Allow-Credentials' 'true';
                add_header 'Access-Control-Allow-Headers' 'Origin, Referer, Content-Type';

# Tell client that this pre-flight info is valid for 20 days

                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                add_header 'Content-Length' 0;
                return 204;
            }
        }
    }
}
```
My **docker-compose.yml**:
```
version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  isso:
    image: wonderfall/isso
    environment:
      - GID=1000
      - UID=1000
    volumes:
      - ./isso/config:/config
      - ./isso/db:/db
```
My **isso.conf**:
```
[general]
dbpath = /db/comments.db
name = isso
host =
    http://Aerial.ml/
    https://Aerial.ml/

[server]
listen = http://0.0.0.0:8082/
```

Here is my **netlify.toml** redirect:
```
[[redirects]]
  from = "/isso/*"
  to = "https://toodoo.ml/:splat"
  status = 200
  force = true
```

And finally my **single.html**:
```
{{ "<!-- isso -->" | safeHTML }}
<script data-isso="{{ .Site.BaseURL }}isso/" src="{{ .Site.BaseURL }}isso/js/embed.min.js"></script>
{{ "<!-- end isso -->" | safeHTML }}

{{"<!-- begin comments //-->" | safeHTML}}
<section id="isso-thread">
</section>
{{"<!-- end comments //-->" | safeHTML}}
```
