### ISSUE TITLE
static javascript content type charset header not set

### ISSUE THREAD

**Issue by bastidest** [posativ/isso#607]
# Description
The charset for the distributed javascript file is not set in the response header, which leads to an error in the browser that implicitly assumes the file is "US-ASCII" encoded.

**Current**
```
Content-Type: application/javascript
```
**Expected**
```
Content-Type: application/javascript; charset=UTF-8
```

The i18n section of the `/js/embed.min.js` javascript therefore has encoding errors:
```
"comment-confirm":"ÐŸÐ¾Ñ‚Ð²ÑŠÑ€Ð¶Ð´ÐµÐ½Ð¸Ðµ"
```

# Used configuration
**docker-compose.yml**
```
version: '3'

services:
  isso:
    image: wonderfall/isso@sha256:1ec8ce977fa9b68d2b513a93d89abf0bcca250d49781e4e279f2ace85519a767
    environment:
      - GID=1000
      - UID=1000
      - LANG=C.UTF-8
    volumes:
      - ./data/isso/config:/config
      - ./data/isso/db:/db
    ports:
      - 8888:8080
```
**isso.conf**
```
[general]
dbpath = /db/comments.db
host = https://redacted.com
[server]
listen = http://0.0.0.0:8080/
```

Curl request
```
curl -sSL -D - http://localhost:8888/js/embed.min.js -o /dev/null
HTTP/1.1 200 OK
Server: gunicorn/20.0.4
Date: Tue, 31 Dec 2019 10:11:15 GMT
Connection: close
Etag: "wzsdm-1577786490-68688-492700795"
Cache-Control: max-age=43200, public
Expires: Tue, 31 Dec 2019 22:11:15 GMT
Content-Type: application/javascript
Content-Length: 68688
Last-Modified: Tue, 31 Dec 2019 10:01:30 GMT
Access-Control-Allow-Origin: http://invalid.local
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: HEAD, GET, POST, PUT, DELETE
Access-Control-Allow-Headers: Origin, Referer, Content-Type
Access-Control-Expose-Headers: X-Set-Cookie, Date
```

# Possible causes
I might be on the wrong path because I never have used any of the libraries, but the Werkzeug documentation says:

> Special note for mimetype and content_type: For most mime types mimetype and content_type work the same, the difference affects only ‘text’ mimetypes. If the mimetype passed with mimetype is a mimetype starting with text/, the charset parameter of the response object is appended to it. In contrast the content_type parameter is always added as header unmodified.

Werkzeug's source code suggests that there was a change in this behavior in Version 15.x:
https://github.com/pallets/werkzeug/blob/9844e0447e63366273c8b9f9f2400e19b45532d1/src/werkzeug/utils.py#L306-L316

Setting `werkzeug==0.16.0` in `setup.py` and rebuilding the docker image did not help.
