### ISSUE TITLE
CSS: Isso should not affect other elements on the site

### ISSUE THREAD

**Issue by neverpanic** [posativ/isso#84]
Including the Isso embed.min.js loads the Isso CSS which might change the layout of the site. Especially hazardous are the lines

``` css
* {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
```

generated by isso/css/neat/grid/_grid.scss because isso/css/neat/settings/_grid.scss contains `$border-box-sizing: true !default;`. Isso should not ship global rules that affect all elements in a page, like the `*` selector does.

Other CSS rules set by Isso that aren't necessarily a good idea are:

``` css
a {
  text-decoration: none;
}
```

and everything not prefixed with "isso", such as `.parent-highlight` and `.postbox`.
