### ISSUE TITLE
Isso doesn't work with Sub-URI multi-site / multiple website setup

### ISSUE THREAD

**Issue by taoeffect** [posativ/isso#925]
## Checklist
- [x] I am running the latest version. Installing Isso from GitHub from the `master` branch does not fix my issue
- [x] I have checked the [troubleshooting guide](https://isso-comments.de/docs/guides/troubleshooting/)
- [x] I have searched the [open issues](https://github.com/posativ/isso/issues), but my issue has not already been reported

## What is not working?

According to this documentation it is possible to setup ISSO so that everything gets routed through a `/isso/` path: https://isso-comments.de/docs/reference/multi-site-sub-uri/#sub-uri

This doesn't work.

ISSO will still make multiple requests to the root domain that do not follow this path, and the documentation isn't clear on how to fix this.

For example, ISSO will try to connect to `/?uri=...`, `/new?uri=...`, `/config`, `/css/isso.css`, and possibly other paths.

This makes it impossible to run ISSO on the same website as the blog.

## How can one reproduce this issue?

My nginx setup looks something like this:

```conf
server {
  server_name blog.domain.tld ;
  root /var/www/blog.domain.tld;
  listen 443 ssl;
  listen 80;
  ssl_certificate /etc/letsencrypt/live/blog.domain.tld/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/blog.domain.tld/privkey.pem;
  location / {
    try_files $uri $uri/;
    add_header Cache-Control "private, max-age=0, no-cache";
  }
  location /isso {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Script-Name /isso;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://isso:8081;
  }
}
```

My `isso.cfg` looks something like this:

```ini
[general]
name = isso
host = http://blog.domain.tld/
dbpath = /config/comments.db
gravatar = true

[guard]
enabled = true
ratelimit = 2
```

My `docker-compose.yml` has a service that looks something like this:

```yml
  isso:
    # https://github.com/isso-comments/placeholder/blob/master/Dockerfile
    image: ghcr.io/isso-comments/isso:0.13.0
    command: ${ISSO_CMD:-/isso/bin/gunicorn -b 0.0.0.0:8081 -w 4 --preload isso.run --worker-tmp-dir /dev/shm}
    depends_on:
      - logs
    logging:
      driver: fluentd
      options:
        tag: "{{.Name}}.log"
    expose:
      - "8081"
    extra_hosts:
      - "blog.domain.tld:192.168.1.17"
    volumes: # save config to vol/isso/isso.cfg
      - ./vol/isso:/config
      - ./cache/localtime:/etc/localtime:ro
```

For local development, I've also added an alias in `/etc/hosts` on the host machine for `blog.domain.tld` that points to `127.0.0.1` and have added a similar entry to the docker container via `extra_hosts`.
